AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation template to create an IAM role with a policy that grants S3 and IAM access.

Resources:
  MyIAMRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Federated: "arn:aws:iam::471112521381:oidc-provider/api.bitbucket.org/2.0/workspaces/drl_admin/pipelines-config/identity/oidc"
            Action: "sts:AssumeRoleWithWebIdentity"
            Condition:
              StringLike:
                "api.bitbucket.org/2.0/workspaces/drl_admin/pipelines-config/identity/oidc:sub":
                  - "{c8b2ab78-e062-4a40-aa88-4bd21e900f08}:*"
                  - "{c8b2ab78-e062-4a40-aa88-4bd21e900f07}:*"
                  - "{c8b2ab78-e062-4a40-aa88-4bd21e900f06}:*"
              IpAddress:
                "aws:SourceIp":
                  - "34.199.54.113/32"
                  - "34.232.25.90/32"
                  - "34.232.119.183/32"
                  - "34.236.25.177/32"
                  - "35.171.175.212/32"
                  - "52.54.90.98/32"
                  - "52.202.195.162/32"
                  - "52.203.14.55/32"
                  - "52.204.96.37/32"
                  - "34.218.156.209/32"
                  - "34.218.168.212/32"
                  - "52.41.219.63/32"
                  - "35.155.178.254/32"
                  - "35.160.177.10/32"
                  - "34.216.18.129/32"
      Path: "/"
      RoleName: "MyExampleRole"

  MyIAMPolicy:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyName: "MyExamplePolicy"
      Roles:
        - Ref: MyIAMRole
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
              - "s3:GetObject"
              - "s3:ListBucket"
              - "s3:PutObject"
              - "s3:DeleteObject"
            Resource:
              - "arn:aws:s3:::example-bucket"
              - "arn:aws:s3:::example-bucket/*"
          - Effect: "Allow"
            Action:
              - "iam:ListUsers"
              - "iam:GetUser"
              - "iam:CreateUser"
              - "iam:DeleteUser"
            Resource:
              - "*"

Outputs:
  RoleName:
    Description: "The name of the IAM role"
    Value: !Ref MyIAMRole
  RoleArn:
    Description: "The ARN of the IAM role"
    Value: !GetAtt MyIAMRole.Arn
  PolicyName:
    Description: "The name of the IAM policy"
    Value: !Ref MyIAMPolicy
